include: package:flutter_lints/flutter.yaml

linter:
  rules:
    curly_braces_in_flow_control_structures: false
    avoid_print: false  
    prefer_single_quotes: true
    prefer_const_constructors : false
    prefer_const_literals_to_create_immutables : false
     
